# .github/workflows/ci.yml

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    - name: Debug bundle
      run: |
        echo ruby -v; ruby -v
        echo bundle -v; bundle -v

        # List all installed gems
        echo bundle list; bundle list
        
        # Show detailed information about a specific gem
        echo bundle show bundler; bundle show bundler
                
        # Check if all required gems are installed
        echo bundle check; bundle check

        # Display the dependency tree
        # echo bundle viz; bundle graph



    - name: Build site
      run: |
        rm -rf _site
        mkdir -p _site/blog
        bundle exec jekyll build --source . --destination _site --config _config.yml --drafts

    - name: Set permissions on _site
      run: chmod -R a-w _site

    # - name: Build site
    #   run: bundle exec jekyll build

    - name: Check date consistency in _posts
      run: bin/check_dates

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _site
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        enable_jekyll: false
        disable_nojekyll: false

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: _site
    #     publish_branch: gh-pages

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: _site

    # - name: Deploy to GitHub Pages
    #   uses: actions/deploy-pages@v3
    #   with:
    #     branch: gh-pages
    #     folder: _site

    # - name: Deploy to GitHub Pages
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: site
    #     path: _site/
